### ISSUE TITLE
Unable to run install Script

### ISSUE THREAD

**Issue by CookieCr2nk** [Michael-Sebero/CoolRune#2]
Hello,

I wanted to test the CoolRune Install Script on a VM, but I encountered the following error:

![grafik](https://github.com/user-attachments/assets/8625d4ce-44e1-44a9-a2f5-cfe13faa83be)

Here is the output of neofetch:

![grafik](https://github.com/user-attachments/assets/f3aa30d3-c3d5-4bca-9c85-6a3be53aa6cd)

If you need more information, you can ask me.

Kind regards,

CookieCr2nk

**Comment by Michael-Sebero** [comment]
I'm aware of this issue and I'll release an install script just for VMs soon. All you'd need to remove from the install script is **grub-mkconfig -o/boot/grub/grub.cfg** and **grub-install**.
![screenshot_20241216-112000](https://github.com/user-attachments/assets/2d0a12a6-25e1-4309-abb0-a8829d7ee844)

**Comment by CookieCr2nk** [comment]
Hello,

I now tried it with the new installer-vm.sh and get following error:

![grafik](https://github.com/user-attachments/assets/d90e177f-a5bb-4338-853b-ead595aa8dab)


Kind regards,

Noa Joder

**Comment by Michael-Sebero** [comment]
My bad, a detail didn't save right in the editor. If you have any other issues provide me details about which variant you're installing and what VM you're using. All the VM tests I've done with CoolRune have been done in QEMU.

**Comment by CookieCr2nk** [comment]
Hello,

Thanks, i will test it. Another Question, why at the end the script will make /home/<user> writable for all users (chmod 777)? That's bad.


Kind regards,

Noa Joder

**Comment by CookieCr2nk** [comment]
I installed also artix on QEMU, but after the Install, artix isn't able to boot.

![grafik](https://github.com/user-attachments/assets/f82c4414-25c9-43ea-a527-c59febca168c)

**Comment by Michael-Sebero** [comment]
I see what happened, I removed the wrong grub step initially for the VM script (rough week).  This step is included again but let me know if you experience a blank screen post-install + tell me what variant you're trying to install.

**Comment by CookieCr2nk** [comment]
Thank you, know it seems to work :)

**Comment by Michael-Sebero** [comment]
No problem.
